#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

case $BLOCK_BUTTON in
#	3) notify-send "🔋 Battery module" "🔋: discharging
	3) notify-send " : Battery module" " : discharging
 : not charging
 : stagnant charge
 : charging
 : charged
 : battery very low!
- Scroll to change adjust xbacklight." ;;
 	4) brightnessctl -q s +1% && sh ~/.config/scripts/xbacklight.sh ;;
 	5) brightnessctl -q s 1%- && sh ~/.config/scripts/xbacklight.sh ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# acpi alternative
# acpi | sed "s/Battery [0-9]: //;s/[Dd]ischarging, /🔋/;s/[Nn]ot charging, /🛑/;s/[Cc]harging, /🔌/;s/[Uu]nknown, /♻️/;s/[Ff]ull, /⚡/;s/ \(remaining\|until charged\)//"; exit

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT1
do
	# Get its remaining capacity and charge status.
	capacity=$(cat "$battery"/capacity 2>/dev/null) || break
	#status=$(sed "s/[Dd]ischarging/   /;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown/♻️/;s/[Ff]ull/ /" "$battery"/status)

	# If it is discharging and 25% or less, we will add a   as a warning.

	if [ "$capacity" -gt 90 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#5faf1b^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 80 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#76b214^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 75 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#8cb60e^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 70 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#8db80d^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 60 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#b4bb11^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 50 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#beb000^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 40 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#c7a500^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 30 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#ce9900^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 25 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#ca7d00^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 20 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#c45e00^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 10 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#bc3d00^   ^d^/;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 5 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#b20000^   /;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
       elif [ "$capacity" -gt 1 ]; then
	        status=$(sed "s/[Dd]ischarging/^c#b20000^   /;s/[Nn]ot charging/  /;s/[Cc]harging/   /;s/[Uu]nknown//;s/[Ff]ull/ /" "$battery"/status)
  fi

	printf "%s%s%s%% " "$status" "$warn" "$capacity"
	unset warn
done | sed 's/ *$//'
