#!/bin/sh

clock=$(date '+%I')

. sb-theme
case "$clock" in
	"00") icon="^c$color^  ^d^" ;;
	"01") icon="^c$color^  ^d^" ;;
	"02") icon="^c$color^  ^d^" ;;
	"03") icon="^c$color^  ^d^" ;;
	"04") icon="^c$color^  ^d^" ;;
	"05") icon="^c$color^  ^d^" ;;
	"06") icon="^c$color^  ^d^" ;;
	"07") icon="^c$color^  ^d^" ;;
	"08") icon="^c$color^  ^d^" ;;
	"09") icon="^c$color^  ^d^" ;;
	"10") icon="^c$color^  ^d^" ;;
	"11") icon="^c$color^  ^d^" ;;
	"12") icon="^c$color^  ^d^" ;;
esac

#       3) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -D ~/.config/calcurse -d3)" ;;
	2) setsid -f "$TERMINAL" -e calcurse -D ~/.config/calcurse ;;
	3) notify-send "  Time/date module  " "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

#date "+%Y %b %d (%a) $icon%I:%M%p" # Original (Luke's) Format
#date "+%a, %b %d $icon%I:%M:%S %p"  # If you want seconds
printf '%s' "$(date "+%a, %b %d $icon%-I:%M:%S %p")"  # If you want seconds w/ color
#printf '^c#FFFFFF^ %-1s^d^' "$(date "+%l:%M $icon%p")"  # ex. 9:42 [icon] pm
#date "+%a, %b %d  $icon %I:%M %p"
#	"00") icon="🕛 " ;;
#	"01") icon="🕐 " ;;
#	"02") icon="🕑 " ;;
#	"03") icon="🕒 " ;;
#	"04") icon="🕓 " ;;
#	"05") icon="🕔 " ;;
#	"06") icon="🕕 " ;;
#	"07") icon="🕖 " ;;
#	"08") icon="🕗 " ;;
#	"09") icon="🕘 " ;;
#	"10") icon="🕙 " ;;
#	"11") icon="🕚 " ;;
#	"12") icon="🕛 " ;;
