#!/bin/sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.

# 📡: no wifi connection
# 📶: wifi connection with quality
# ❎: no ethernet
# 🌐: ethernet working
case $BLOCK_BUTTON in
	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
	3) notify-send "  Internet module" "\- Click to connect
 : no wifi connection
 : wifi connection with quality
 : no ethernet
 : ethernet working
" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
  down) case "$(cat /sys/class/net/e*/operstate 2>/dev/null || echo )" in
          down) ethicon=""; wifiicon="" ;;
          up) ethicon=" " ;;
          *) ethicon="" ;;
        esac
        wifiicon="" ;;
	up) wifiicon="$(awk '/^\s*w/ { print "^c#88C0D0^  ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)" ;;
esac

printf "%s%s\n" "$wifiicon" "$ethicon"
