#!/bin/sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.

# 📡: no wifi connection
# 📶: wifi connection with quality
# ❎: no ethernet
# 🌐: ethernet working
case $BLOCK_BUTTON in
	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
	3) notify-send "  Internet module" "\- Click to connect
 : no wifi connection
 : wifi connection with quality
 : no ethernet
 : ethernet working
" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

con_quality=$(awk '/^\s*w/ { print int($3 * 100 / 70) }' /proc/net/wireless) || break

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
  down) case "$(cat /sys/class/net/e*/operstate 2>/dev/null || echo )" in
          down) ethicon=""; wifiicon="" ;;
          up) ethicon=" " ;;
          *) ethicon="" ;;
        esac
        wifiicon="" ;;
  up) wifiicon="^c#5faf1b^  ^d^"
  	# if [ "$con_quality" -gt 90 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#5faf1b^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 80 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#6db117^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 70 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#83b511^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 60 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#8cb60e^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 50 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#c7a500^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 40 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#ce9900^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 30 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#cb8800^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 20 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#c15300^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 10 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#bb3100^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  # elif [ "$con_quality" -gt 1 ]; then
  #   wifiicon="$(awk '/^\s*w/ { print "^c#b20000^   ^d^", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
  #     fi
esac

printf "%s%s\n" "$wifiicon" "$ethicon"
