#!/bin/bash

. sb-theme
title=$(playerctl -p spotify metadata --format "{{title}}")
artist=$(playerctl -p spotify metadata --format "{{title}}")
title_artist=$(playerctl -p spotify metadata --format "{{title}} - {{artist}}")
printf "%s" "$title_artist"
