#!/bin/sh

stock="SPXS"

spxs() {
. $HOME/.config/suckless/dwmblocks/perl/query_stock $stock | awk '{printf ("%.2f ", $3+0.005)}'
}

spxs_dc=$(sh $HOME/.config/suckless/dwmblocks/perl/query_stock $stock | awk '{print $4}')
round_dc() {
  echo $spxs_dc | awk '{printf "%.2f", $1*10}' | awk '{printf "%.0f", $1}'
}

if [[ $(bc <<< "$(round_dc)") -gt 0 ]]; then
  spxs_daily="$(sh $HOME/.config/suckless/dwmblocks/perl/query_stock $stock | awk '{print $4}')";
  echo "^c#e1b55b^\$$(spxs)"^c#6db111^$spxs_dc ^d^
elif [ $(bc <<< "$(round_dc)") -lt 0 ]; then
  spxs_daily="$(sh $HOME/.config/suckless/dwmblocks/perl/query_stock $stock | awk '{print $4}')";
  echo "^c#e1b55b^\$$(spxs)"^c#d13232^$spxs_dc ^d^
fi

# echo "$(spxs)"$spxs_daily
