#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "  Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send "   Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs.
- Middle click to open htop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

. sb-theme

#free --mebi | sed -n '2{p;q}' | awk '{printf ("   %2.2fGiB/%2.2fGiB\n", ( $3 / 1024), ($2 / 1024))}' # memory in X.X GB form
swap() { 
  free --mega | sed -n '3{p;q}' | awk '{printf ("%2.0f MB\n", ( $3 / 1))}' # memory in xxxx MB form
}

printf "^c$color^%s^d^%s" " " "$(swap)"

# Brain Icon in case I ever need it 🧠 
