#!/bin/sh

case "$(basename $0)" in 
  sb-cpu) color=#C73636 ;;
  sb-memory) color=#e3a26f ;;
  sb-clock) color=#ECBE60 ;;
  sb-swap) color=#ffc517 ;;
  sb-disk) color=#86C154 ;;
  sb-volume) color=#99c1e9 ;;
  sb-music_name) color=#ced2d9 ;;
  sb-music_time) color=#ced2d9 ;;
  *) color=#FFFFFF ;;
esac

# Weather colors
rain="#c7c7c7"
wl="#99c1e9"
wh="#ffc517"
