#!/bin/sh

case "$(basename $0)" in 
  cpu) color=#C73636 ;;
  memory) color=#e3a26f ;;
  clock) color=#ECBE60 ;;
  swap) color=#ffc517 ;;
  disk) color=#86C154 ;;
  volume) color=#99c1e9 ;;
  music_name) color=#ced2d9 ;;
  music_time) color=#ECBE60 ;;
  *) color=#FFFFFF ;;
esac

# Weather colors
rain="#67a8e9"
wl="#99c1e9"
wh="#ffc517"
