#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pavucontrol ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
#	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
	3) notify-send "  Volume module" "\- Shows volume ,  if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

#[ $(pamixer --get-mute) = true ] && echo 🔇 && exit
[ $(pamixer --get-mute) = true ] && echo  Muted && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
#	icon="🔊"
	icon="  "
elif [ "$vol" -lt "35" ]; then
#	icon="🔈"
	icon="  "
else
#	icon="🔉"
	icon="  "
fi

printf "^c#99c1e9^ %s^d^^c#FFFFFF^%s^d^\n" "$icon" "$vol%"
