#!/bin/sh

# Displays todays precipication chance (☔) and daily low (🥶) and high (🌞).
# Usually intended for the statusbar.

# If we have internet, get a weather report from wttr.in and store it locally.
# You could set up a shell alias to view the full file in a pager in the
# terminal if desired. This function will only be run once a day when needed.
weatherreport="${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport"
getforecast() { curl -sf "wttr.in/$LOCATION" > "$weatherreport" || exit 1 ;}

# Some very particular and terse stream manipulation. We get the maximum
# precipitation chance and the daily high and low from the downloaded file and
# display them with coresponding emojis.
showweather() { printf "%s" "$(sed '16q;d' "$weatherreport" | grep -wo "[0-9]*%" | sort -rn | sed "s/^/  /g;1q" | tr -d '\n')" sed '13q;d' "$weatherreport" | grep -o "m\\([-+]\\)*[0-9]\\+" | sed 's/+//g' | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " " $1 "°/","" $2 "°"}' ;}

rain_chance() { printf "%s" "$(sed '16q;d' "$weatherreport" | grep -wo "[0-9]*%")" | sed 's/%//' | paste -sd+ | bc | awk '{printf "%d",(($1/4)+0.5)}' | sed "s/^/  /g;1q" | tr -d '\n' ;}
weather_low() { sed '13q;d' "$weatherreport" | grep -o "m\\([-+]\\)*[0-9]\\+" | sed 's/+//g' | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print $1 "F"}' ;}
weather_high() { sed '13q;d' "$weatherreport" | grep -o "m\\([-+]\\)*[0-9]\\+" | sed 's/+//g' | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print $2 "F"}' ;}
current_temp() { sed '4q;d' "$weatherreport" | grep -o "m\\([-+]\\)*[0-9]\\+" | tr '\n|m' ' ' | awk '{print $1 "F"}';}
# °

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e less -Srf "$weatherreport" ;;
	2) getforecast && showweather ;;
	3) notify-send "  Weather module " "\- Left click for full forecast.
- Middle click to update forecast.
: Chance of rain/snow
 : Daily low
 : Daily high" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# The test if our forcecast is updated to the day. If it isn't download a new
# weather report from wttr.in with the above function.
# [ "$(stat -c %y "$weatherreport" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] ||
getforecast

. theme

printf "^c$wh^%s^d^^c$rain^%s^d^" "$(current_temp | sed 's/+//')" "$(rain_chance)%"
# printf "^c$wl^%s^d^/^c$wh^%s^d^^c$rain^%s^d^" "$(weather_low)" "$(weather_high)" "$(rain_chance)%"
# printf "^c$wl^%s^d^/^c$wh^%s^d^" "$(weather_low)" "$(weather_high)"
